framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        
when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['martin@kaamaa.de']


#framework:
#    mailer:
#        dsn: '%env(MAILER_DSN)%'
#        #envelope:
#            #mail_from: '%env(MAIL_FROM)%'  
#        
#when@dev:
#    framework:
#        mailer:
#            envelope:
#                recipients: ['martin@kaamaa.de']