security:
      
    providers:
      app_user_provider:
          entity:
              class: App\Entity\FresAccounts
              property: username
       
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 
            id: 'App\Security\Hasher\CustomPasswordHasher'    
   
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false 
              
        main:
            custom_authenticators:
              - App\Security\LoginFormAuthenticator 
      
            entry_point: App\Security\LoginFormAuthenticator   # <- WICHTIG    
            lazy: true
            stateless: false
            provider: app_user_provider
                
            #form_login:
            #    login_path: app_login
            #    check_path: app_login
            #    default_target_path: _weeksview
            #    always_use_default_target_path: true
            #    #enable_csrf: true

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 
                # 30 days in seconds
                path: /
                # always_remember_me: true   
                user_provider: app_user_provider
                #signature_properties: ['username', 'clientid']

            logout:
                path: app_logout          # Route-Name ODER Pfadname, s. Punkt 2
                target: app_login         # Route-Name oder URL
                invalidate_session: true
                delete_cookies:
                    REMEMBERME: ~
                clear_site_data: ['cookies', 'storage', 'executionContexts'] # optional (>=6.3)

            #json_login:
                # api_login is a route we will create below
                #check_path: app_json
                #remember_me: true
                #username_path: username
                #password_path: password
                

    access_control:
        - { path: ^/sunrise_sunset, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/notloggedin, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        # auskommentieren dieser Zeilen führt dazu, dass Login über Joomla funktioniert
        #- { path: ^/loginwithcredentials, roles: PUBLIC_ACCESS }
        #- { path: ^/login_json, roles: PUBLIC_ACCESS }
        - { path: ^/start_session, roles: PUBLIC_ACCESS }
        - { path: ^/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/editaircraft, roles: ROLE_SYSTEM_ADMIN }  
        - { path: ^/getusermail, roles: ROLE_SYSTEM_ADMIN }  
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_GUEST }  
       
        
    role_hierarchy:
        ROLE_GUEST:
        ROLE_PILOT:        [ROLE_GUEST]
        ROLE_FI:           [ROLE_PILOT, ROLE_GUEST]
        ROLE_ADMIN:        [ROLE_FI, ROLE_PILOT, ROLE_GUEST]
        ROLE_SYSTEM_ADMIN: [ROLE_ADMIN, ROLE_FI, ROLE_PILOT, ROLE_GUEST]
        ROLE_GLOBAL_ADMIN: [ROLE_SYSTEM_ADMIN, ROLE_ADMIN, ROLE_FI, ROLE_PILOT, ROLE_GUEST, ROLE_ALLOWED_TO_SWITCH]
       
       
